<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use App\Models\User;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categoryMap = Category::pluck('id', 'name');
        $userIds = User::pluck('id')->all();

        if (empty($userIds) || $categoryMap->isEmpty()) {
            return;
        }

        $products = [
            [
                'name' => 'iPhone 15 Pro Max 256GB Titan Xanh',
                'category' => 'Điện tử - Điện thoại',
                'price' => 32990000,
                'original_price' => 36990000,
                'description' => 'iPhone 15 Pro Max màu titan xanh, pin 98%, chưa sửa chữa.',
                'short_description' => 'Máy 99%, đầy đủ phụ kiện và hóa đơn.',
                'condition' => 'like_new',
                'location' => 'Quận 1, TP. HCM',
                'seller_name' => 'Nguyễn Minh Huy',
                'contact_phone' => '0987123456',
                'contact_email' => 'minhhuy@example.com',
                'contact_method' => 'phone',
                'sku' => 'APL-IP15PM-256-TB',
                'origin' => 'Apple VN/A',
                'warranty' => '8 tháng',
                'attachments' => 'Hộp, cáp USB-C, ốp MagSafe, kính cường lực',
                'additional_info' => 'Tặng kèm AppleCare+ còn 10 tháng.',
                'quantity' => 2,
                'status' => 'published',
                'view_count' => 412,
                'images' => [
                    'images/products/iphone-15-pro-max-1.jpg',
                    'images/products/iphone-15-pro-max-2.jpg',
                    'images/products/iphone-15-pro-max-3.jpg',
                    'images/products/iphone-15-pro-max-4.jpg',
                    'images/products/iphone-15-pro-max-5.jpg',
                ],
            ],
            [
                'name' => 'Samsung Galaxy Z Fold5 512GB Kem Ivory',
                'category' => 'Điện tử - Điện thoại',
                'price' => 34990000,
                'original_price' => 39990000,
                'description' => 'Galaxy Z Fold5 màu kem 512GB, gập mở mượt, không trầy xước.',
                'short_description' => 'Full phụ kiện, bao test 7 ngày.',
                'condition' => 'good',
                'location' => 'Cầu Giấy, Hà Nội',
                'seller_name' => 'Trần Thu Trang',
                'contact_phone' => '0912345678',
                'contact_email' => 'trangtran@example.com',
                'contact_method' => 'zalo',
                'sku' => 'SMS-ZF5-512-IV',
                'origin' => 'Samsung VN',
                'warranty' => '12 tháng',
                'attachments' => 'Hộp, cáp USB-C, S-Pen Fold Edition, bao da',
                'additional_info' => 'Hỗ trợ trả góp qua thẻ.',
                'quantity' => 1,
                'status' => 'published',
                'view_count' => 368,
                'images' => [
                    'images/products/samsung-galaxy-z-fold5-1.jpg',
                    'images/products/samsung-galaxy-z-fold5-2.jpg',
                    'images/products/samsung-galaxy-z-fold5-3.jpg',
                    'images/products/samsung-galaxy-z-fold5-4.jpg',
                    'images/products/samsung-galaxy-z-fold5-5.jpg',
                ],
            ],
            [
                'name' => 'Google Pixel 8 Pro 128GB Xanh Biển',
                'category' => 'Điện tử - Điện thoại',
                'price' => 22490000,
                'original_price' => 25990000,
                'description' => 'Google Pixel 8 Pro bản US, camera ấn tượng, hỗ trợ eSIM.',
                'short_description' => 'Máy 97%, kèm sạc nhanh 30W và ốp Spigen.',
                'condition' => 'good',
                'location' => 'Thanh Xuân, Hà Nội',
                'seller_name' => 'Đỗ Văn Lộc',
                'contact_phone' => '0905223344',
                'contact_email' => 'locdo@example.com',
                'contact_method' => 'phone',
                'sku' => 'GOO-PX8P-128-O',
                'origin' => 'Google Store US',
                'warranty' => '8 tháng',
                'attachments' => 'Hộp, sạc 30W, ốp lưng, miếng dán',
                'additional_info' => 'Đã đăng ký bảo hành quốc tế.',
                'quantity' => 3,
                'status' => 'published',
                'view_count' => 219,
                'images' => [
                    'images/products/google-pixel-8-pro.jpg',
                    'images/products/google-pixel-8-pro-2.jpg',
                    'images/products/google-pixel-8-pro-3.jpg',
                    'images/products/google-pixel-8-pro-4.jpg',
                    'images/products/google-pixel-8-pro-5.jpg',
                ],
            ],
            [
                'name' => 'iPad Air M2 11" Wi-Fi 256GB Xanh Dương',
                'category' => 'Điện tử - Điện thoại',
                'price' => 18990000,
                'original_price' => 21990000,
                'description' => 'iPad Air M2 11 inch dùng nhẹ cho học online, ngoại hình đẹp.',
                'short_description' => 'Kèm Magic Keyboard Folio và Apple Pencil Gen 2.',
                'condition' => 'like_new',
                'location' => 'Quận 3, TP. HCM',
                'seller_name' => 'Lê Phương Nam',
                'contact_phone' => '0909887766',
                'contact_email' => 'namle@example.com',
                'contact_method' => 'zalo',
                'sku' => 'APL-IPAD-AIR-M2-256-BL',
                'origin' => 'Apple VN/A',
                'warranty' => '10 tháng',
                'attachments' => 'Hộp, cáp USB-C, Magic Keyboard, Apple Pencil',
                'additional_info' => 'Giao nhanh nội thành trong 2 giờ.',
                'quantity' => 2,
                'status' => 'published',
                'view_count' => 287,
                'images' => [
                    'images/products/ipad-air-m2.jpg',
                    'images/products/ipad-air-m2-2.jpg',
                    'images/products/ipad-air-m2-3.jpg',
                    'images/products/ipad-air-m2-4.jpg',
                    'images/products/ipad-air-m2-5.jpg',
                ],
            ],
            [
                'name' => 'MacBook Air 15" M3 16GB/512GB Bạc',
                'category' => 'Điện tử - Điện thoại',
                'price' => 32990000,
                'original_price' => 38990000,
                'description' => 'MacBook Air M3 15 inch cấu hình 16GB/512GB, pin ít chu kỳ.',
                'short_description' => 'Máy 99%, bàn phím US, chưa kích hoạt AppleCare.',
                'condition' => 'like_new',
                'location' => 'Ba Đình, Hà Nội',
                'seller_name' => 'Phạm Hoàng Long',
                'contact_phone' => '0918993344',
                'contact_email' => 'longpham@example.com',
                'contact_method' => 'phone',
                'sku' => 'APL-MBA15-M3-16-512-SL',
                'origin' => 'Apple VN/A',
                'warranty' => '11 tháng',
                'attachments' => 'Hộp, sạc 35W, dây USB-C, túi chống sốc WiWU',
                'additional_info' => 'Tặng phần mềm Office 365 bản quyền 1 năm.',
                'quantity' => 1,
                'status' => 'published',
                'view_count' => 331,
                'images' => [
                    'images/products/macbook-air-15-m3-1.jpg',
                    'images/products/macbook-air-15-m3-2.jpg',
                    'images/products/macbook-air-15-m3-3.jpg',
                    'images/products/macbook-air-15-m3-4.jpg',
                    'images/products/macbook-air-15-m3-5.jpg',
                ],
            ],
            [
                'name' => 'Tai nghe Sony WH-1000XM5 Đen',
                'category' => 'Điện tử - Điện thoại',
                'price' => 6490000,
                'original_price' => 8490000,
                'description' => 'Tai nghe Sony WH-1000XM5 chống ồn chủ động, dùng chưa tới 6 tháng.',
                'short_description' => 'Pin 25 giờ, đi kèm túi đựng và cáp USB-C.',
                'condition' => 'good',
                'location' => 'Tân Bình, TP. HCM',
                'seller_name' => 'Hoàng Gia Bảo',
                'contact_phone' => '0933399988',
                'contact_email' => 'baohoang@example.com',
                'contact_method' => 'phone',
                'sku' => 'SNY-WH1000XM5-BK',
                'origin' => 'Sony Vietnam',
                'warranty' => '7 tháng',
                'attachments' => 'Hộp, cable 3.5mm, cable USB-C, túi đựng',
                'additional_info' => 'Tặng kèm adapter Bluetooth cho PC.',
                'quantity' => 4,
                'status' => 'published',
                'view_count' => 178,
                'images' => [
                    'images/products/sony-wh-1000xm5-1.jpg',
                    'images/products/sony-wh-1000xm5-2.jpg',
                    'images/products/sony-wh-1000xm5-3.jpg',
                    'images/products/sony-wh-1000xm5-4.jpg',
                    'images/products/sony-wh-1000xm5-5.jpg',
                ],
            ],
            [
                'name' => 'Máy hút bụi Dyson V11 Absolute',
                'category' => 'Đồ gia dụng',
                'price' => 11800000,
                'original_price' => 16990000,
                'description' => 'Máy hút bụi Dyson V11 Absolute đầy đủ đầu hút, pin bền, dùng nhẹ.',
                'short_description' => 'Hiển thị LCD, lực hút mạnh, bảo hành chính hãng.',
                'condition' => 'good',
                'location' => 'Quận 7, TP. HCM',
                'seller_name' => 'Ngô Anh Thư',
                'contact_phone' => '0968112233',
                'contact_email' => 'anhthu@example.com',
                'contact_method' => 'phone',
                'sku' => 'DYS-V11-ABS',
                'origin' => 'Dyson Vietnam',
                'warranty' => '9 tháng',
                'attachments' => 'Docking, 6 đầu hút, hướng dẫn sử dụng',
                'additional_info' => 'Tặng kèm bộ lọc HEPA dự phòng.',
                'quantity' => 2,
                'status' => 'published',
                'view_count' => 156,
                'images' => [
                    'images/products/dyson-v11-absolute-1.jpg',
                    'images/products/dyson-v11-absolute-2.jpg',
                    'images/products/dyson-v11-absolute-3.jpg',
                    'images/products/dyson-v11-absolute.png',
                    'images/products/dyson-v11-absolute-5.jpg',
                ],
            ],
            [
                'name' => 'Máy pha cà phê DeLonghi Dedica EC685.M',
                'category' => 'Đồ gia dụng',
                'price' => 5200000,
                'original_price' => 8490000,
                'description' => 'Máy pha cà phê bán tự động DeLonghi Dedica EC685.M, dùng gia đình.',
                'short_description' => 'Vận hành êm, tặng tamper inox và ca đánh sữa.',
                'condition' => 'good',
                'location' => 'Bình Thạnh, TP. HCM',
                'seller_name' => 'Lê Thị Hòa',
                'contact_phone' => '0909884455',
                'contact_email' => 'hoale@example.com',
                'contact_method' => 'phone',
                'sku' => 'DEL-EC685M',
                'origin' => 'DeLonghi Vietnam',
                'warranty' => '6 tháng',
                'attachments' => 'Portafilter, tamper, ca đánh sữa, sách hướng dẫn',
                'additional_info' => 'Tặng kèm 1kg hạt Arabica rang medium.',
                'quantity' => 1,
                'status' => 'published',
                'view_count' => 143,
                'images' => [
                    'images/products/delonghi-dedica-ec685m-1.png',
                    'images/products/delonghi-dedica-ec685m-2.png',
                    'images/products/delonghi-dedica-ec685m-3.png',
                    'images/products/delonghi-dedica-ec685m-4.png',
                    'images/products/delonghi-dedica-ec685m-5.png',
                ],
            ],
            [
                'name' => 'Nồi chiên không dầu Philips XXL HD9650',
                'category' => 'Đồ gia dụng',
                'price' => 4200000,
                'original_price' => 6990000,
                'description' => 'Nồi chiên không dầu Philips XXL HD9650 dung tích 7.3L, điều khiển điện tử.',
                'short_description' => 'Dùng 3 tháng, sạch sẽ, còn bảo hành chính hãng.',
                'condition' => 'good',
                'location' => 'Long Biên, Hà Nội',
                'seller_name' => 'Phạm Thùy An',
                'contact_phone' => '0988332211',
                'contact_email' => 'anthuy@example.com',
                'contact_method' => 'phone',
                'sku' => 'PHI-HD9650-XXL',
                'origin' => 'Philips Vietnam',
                'warranty' => '10 tháng',
                'attachments' => 'Hộp, giỏ chiên, khay nướng',
                'additional_info' => 'Tặng sách công thức 30 món.',
                'quantity' => 1,
                'status' => 'published',
                'view_count' => 132,
                'images' => [
                    'images/products/philips-airfryer-hd9650-1.png',
                    'images/products/philips-airfryer-hd9650-2.png',
                    'images/products/philips-airfryer-hd9650-3.png',
                    'images/products/philips-airfryer-hd9650-4.png',
                    'images/products/philips-airfryer-hd9650-5.png',
                ],
            ],
            [
                'name' => 'Bộ nồi inox Elmich Trimax Classic 5 món',
                'category' => 'Đồ gia dụng',
                'price' => 1950000,
                'original_price' => 3290000,
                'description' => 'Bộ nồi inox Elmich Trimax Classic đáy 5 lớp, dùng được bếp từ.',
                'short_description' => 'Hàng tặng chưa sử dụng, còn nguyên seal.',
                'condition' => 'new',
                'location' => 'Ninh Kiều, Cần Thơ',
                'seller_name' => 'Trương Gia Khánh',
                'contact_phone' => '0911668899',
                'contact_email' => 'giakhanh@example.com',
                'contact_method' => 'phone',
                'sku' => 'ELM-TRIMAX-5PC',
                'origin' => 'Elmich Czech',
                'warranty' => '24 tháng',
                'attachments' => 'Hộp, phiếu bảo hành, sách hướng dẫn',
                'additional_info' => 'Giao hàng miễn phí nội thành, bao kiểm tra hàng.',
                'quantity' => 3,
                'status' => 'published',
                'view_count' => 84,
                'images' => [
                    'images/products/elmich-trimax-classic-1.png',
                    'images/products/elmich-trimax-classic-2.png',
                    'images/products/elmich-trimax-classic-3.png',
                    'images/products/elmich-trimax-classic-4.png',
                    'images/products/elmich-trimax-classic-5.png',
                ],
            ],
            [
                'name' => 'Áo khoác da Zara Biker nam size L',
                'category' => 'Thời trang',
                'price' => 1450000,
                'original_price' => 2890000,
                'description' => 'Áo khoác da Zara kiểu biker màu đen, chất liệu da PU cao cấp, form slim.',
                'short_description' => 'Áo mặc 2 lần, không trầy xước, giữ form tốt.',
                'condition' => 'like_new',
                'location' => 'Bình Thạnh, TP. HCM',
                'seller_name' => 'Võ Bảo Trân',
                'contact_phone' => '0933557799',
                'contact_email' => 'baotran@example.com',
                'contact_method' => 'phone',
                'sku' => 'ZRA-BIKER-L-BLK',
                'origin' => 'Zara Vietnam',
                'warranty' => null,
                'attachments' => 'Tag, móc treo, túi giấy Zara',
                'additional_info' => 'Khuyến mãi kèm khăn choàng len đen.',
                'quantity' => 1,
                'status' => 'published',
                'view_count' => 92,
                'images' => [
                    'images/products/zara-biker-jacke-1.jpg',
                    'images/products/zara-biker-jacke-2.jpg',
                    'images/products/zara-biker-jacke.jpg',
                    'images/products/zara-biker-jacke-4.jpg',
                    'images/products/zara-biker-jacke-5.jpg',
                ],
            ],
            [
                'name' => 'Bộ vest nam Aristino Premium Navy size 52',
                'category' => 'Thời trang',
                'price' => 3500000,
                'original_price' => 5790000,
                'description' => 'Bộ vest Aristino dòng Premium màu xanh navy, chất vải wool blend, may đo chuẩn.',
                'short_description' => 'Vest mặc 1 lần dự tiệc, chưa qua giặt hấp.',
                'condition' => 'like_new',
                'location' => 'Nam Từ Liêm, Hà Nội',
                'seller_name' => 'Phan Thanh Bình',
                'contact_phone' => '0905123456',
                'contact_email' => 'binhphan@example.com',
                'contact_method' => 'zalo',
                'sku' => 'ARI-VEST-52-NAVY',
                'origin' => 'Aristino Vietnam',
                'warranty' => null,
                'attachments' => 'Áo vest, quần tây, áo gile, túi áo, móc treo',
                'additional_info' => 'Bao chỉnh sửa form miễn phí tại showroom Aristino.',
                'quantity' => 1,
                'status' => 'published',
                'view_count' => 107,
                'images' => [
                    'images/products/aristino-vest-navy-1.png',
                    'images/products/aristino-vest-navy-2.png',
                    'images/products/aristino-vest-navy-3.png',
                    'images/products/aristino-vest-navy-4.png',
                    'images/products/aristino-vest-navy-5.png',
                ],
            ],
            [
                'name' => 'Đầm maxi linen Hnoss màu be size M',
                'category' => 'Thời trang',
                'price' => 790000,
                'original_price' => 1590000,
                'description' => 'Đầm maxi linen Hnoss màu be, phù hợp dạo biển hoặc dự tiệc ngoài trời.',
                'short_description' => 'Đầm mới, còn tag, dáng dài chạm mắt cá.',
                'condition' => 'new',
                'location' => 'Quận Hải Châu, Đà Nẵng',
                'seller_name' => 'Đặng Hoàng Phúc',
                'contact_phone' => '0944332211',
                'contact_email' => 'phucdang@example.com',
                'contact_method' => 'phone',
                'sku' => 'HNOSS-LINEN-M-BE',
                'origin' => 'Hnoss Fashion',
                'warranty' => null,
                'attachments' => 'Túi vải Hnoss, móc treo',
                'additional_info' => 'Tặng kèm khăn turban hoa nhí.',
                'quantity' => 2,
                'status' => 'published',
                'view_count' => 65,
                'images' => [
                    'images/products/hnoss-maxi-linen-1.png',
                    'images/products/hnoss-maxi-linen-2.png',
                    'images/products/hnoss-maxi-linen-3.png',
                    'images/products/hnoss-maxi-linen-4.png',
                    'images/products/hnoss-maxi-linen-5.png',
                ],
            ],
            [
                'name' => 'Giày sneaker Adidas Ultraboost 22 Trắng',
                'category' => 'Thời trang',
                'price' => 2200000,
                'original_price' => 4800000,
                'description' => 'Giày Adidas Ultraboost 22 màu trắng size 42, mang 4 lần, đế Boost đàn hồi tốt.',
                'short_description' => 'Giày authentic, fullbox, chưa giặt, còn thơm.',
                'condition' => 'like_new',
                'location' => 'Thủ Đức, TP. HCM',
                'seller_name' => 'Huỳnh Thảo Vy',
                'contact_phone' => '0922664477',
                'contact_email' => 'thaovy@example.com',
                'contact_method' => 'zalo',
                'sku' => 'ADI-UB22-42W',
                'origin' => 'Adidas Vietnam',
                'warranty' => null,
                'attachments' => 'Hộp, dây giày dự phòng, phiếu bảo hành',
                'additional_info' => 'Tặng kèm vớ thể thao Adidas.',
                'quantity' => 1,
                'status' => 'published',
                'view_count' => 121,
                'images' => [
                    'images/products/adidas-ultraboost-22-1.png',
                    'images/products/adidas-ultraboost-22-2.png',
                    'images/products/adidas-ultraboost-22-3.png',
                    'images/products/adidas-ultraboost-22-4.png',
                    'images/products/adidas-ultraboost-22-5.png',
                ],
            ],
            [
                'name' => 'Combo bút máy Lamy Safari + ống mực',
                'category' => 'Sách - Văn phòng phẩm',
                'price' => 1250000,
                'original_price' => 1680000,
                'description' => 'Combo bút máy Lamy Safari ngòi F màu charcoal kèm converter và 5 ống mực.',
                'short_description' => 'Bút mới 100%, chưa chấm mực, hộp nguyên seal.',
                'condition' => 'new',
                'location' => 'Hà Đông, Hà Nội',
                'seller_name' => 'Bùi Lâm',
                'contact_phone' => '0912446688',
                'contact_email' => 'lambui@example.com',
                'contact_method' => 'phone',
                'sku' => 'LAMY-SAFARI-F-SET',
                'origin' => 'Lamy Germany',
                'warranty' => '12 tháng',
                'attachments' => 'Hộp Lamy, converter Z28, 5 ống mực xanh',
                'additional_info' => 'Tặng kèm 1 lọ mực Lamy T52 30ml.',
                'quantity' => 5,
                'status' => 'published',
                'view_count' => 61,
                'images' => [
                    'images/products/lamy-safari-set-1.png',
                    'images/products/lamy-safari-set-2.png',
                    'images/products/lamy-safari-set-3.png',
                    'images/products/lamy-safari-set-4.png',
                    'images/products/lamy-safari-set-5.png',
                ],
            ],
            [
                'name' => 'Sổ tay bullet journal Leuchtturm1917 chấm bi',
                'category' => 'Sách - Văn phòng phẩm',
                'price' => 380000,
                'original_price' => 520000,
                'description' => 'Sổ tay Leuchtturm1917 bản A5 chấm bi màu olive, giấy 80gsm.',
                'short_description' => 'Sổ mới 100%, kèm sticker và bìa bảo vệ.',
                'condition' => 'new',
                'location' => 'Quận 5, TP. HCM',
                'seller_name' => 'Vũ Thị Hải Yến',
                'contact_phone' => '0933884411',
                'contact_email' => 'yenvu@example.com',
                'contact_method' => 'phone',
                'sku' => 'LEU-BUJO-A5-OLV',
                'origin' => 'Leuchtturm Germany',
                'warranty' => null,
                'attachments' => 'Hộp giấy, sticker, template bullet journal',
                'additional_info' => 'Tặng thêm 3 cuộn washi tape trang trí.',
                'quantity' => 6,
                'status' => 'published',
                'view_count' => 54,
                'images' => [
                    'images/products/leuchtturm1917-bujo-1.png',
                    'images/products/leuchtturm1917-bujo-2.png',
                    'images/products/leuchtturm1917-bujo-3.png',
                    'images/products/leuchtturm1917-bujo-4.png',
                    'images/products/leuchtturm1917-bujo-5.png',
                ],
            ],
            [
                'name' => 'Bộ sách Harvard Business Review Essentials (6 cuốn)',
                'category' => 'Sách - Văn phòng phẩm',
                'price' => 950000,
                'original_price' => 1680000,
                'description' => 'Set 6 cuốn Harvard Business Review Essentials bản tiếng Việt, sách mới, chưa đọc.',
                'short_description' => 'Sách bọc plastic, không gấp góc, giấy láng.',
                'condition' => 'new',
                'location' => 'Đống Đa, Hà Nội',
                'seller_name' => 'Nguyễn Minh Huy',
                'contact_phone' => '0987123456',
                'contact_email' => 'minhhuy@example.com',
                'contact_method' => 'phone',
                'sku' => 'HBR-ESSENTIAL-SET6',
                'origin' => 'NXB Trẻ',
                'warranty' => null,
                'attachments' => 'Hộp carton, bookmark HBR',
                'additional_info' => 'Tặng kèm sổ tay ghi chú 80 trang.',
                'quantity' => 4,
                'status' => 'published',
                'view_count' => 76,
                'images' => [
                    'images/products/hbr-essentials-set-1.png',
                    'images/products/hbr-essentials-set-2.png',
                    'images/products/hbr-essentials-set-3.png',
                    'images/products/hbr-essentials-set-4.png',
                    'images/products/hbr-essentials-set-5.png',
                ],
            ],
            [
                'name' => 'Honda SH Mode 2023 ABS đỏ nâu',
                'category' => 'Xe cộ - Phụ tùng',
                'price' => 64900000,
                'original_price' => 73900000,
                'description' => 'Xe tay ga Honda SH Mode ABS 2023 màu đỏ nâu, odo 3.500 km, chính chủ.',
                'short_description' => 'Đăng ký 12/2023, giấy tờ đầy đủ.',
                'condition' => 'good',
                'location' => 'Quận Bình Thạnh, TP. HCM',
                'seller_name' => 'Nguyễn Văn A',
                'contact_phone' => '0977665544',
                'contact_email' => 'vana@example.com',
                'contact_method' => 'phone',
                'sku' => 'HON-SHMODE-2023-RED',
                'origin' => 'Honda Vietnam',
                'warranty' => '18 tháng',
                'attachments' => '2 chìa khóa thông minh, sổ bảo hành, bảo hiểm TNDS',
                'additional_info' => 'Bao sang tên trong ngày, hỗ trợ trả góp ngân hàng.',
                'quantity' => 1,
                'status' => 'published',
                'view_count' => 401,
                'images' => [
                    'images/products/honda-sh-mode-2023-1.jpg',
                    'images/products/honda-sh-mode-2023-2.jpg',
                    'images/products/honda-sh-mode-2023-3.jpg',
                    'images/products/honda-sh-mode-2023-4.jpg',
                    'images/products/honda-sh-mode-2023-5.jpg',
                ],
            ],
            [
                'name' => 'Xe đạp road Giant Contend AR 4 2024',
                'category' => 'Xe cộ - Phụ tùng',
                'price' => 21990000,
                'original_price' => 27990000,
                'description' => 'Xe đạp road Giant Contend AR 4 2024 khung nhôm, groupset Shimano Claris.',
                'short_description' => 'Xe đi 800 km, bảo dưỡng định kỳ tại Giant Store.',
                'condition' => 'good',
                'location' => 'Thủ Đức, TP. HCM',
                'seller_name' => 'Huỳnh Thảo Vy',
                'contact_phone' => '0922664477',
                'contact_email' => 'thaovy@example.com',
                'contact_method' => 'phone',
                'sku' => 'GIA-CONTEND-AR4-2024',
                'origin' => 'Giant Taiwan',
                'warranty' => '20 tháng',
                'attachments' => 'Chân chống, bình nước Giant, bộ vá lốp',
                'additional_info' => 'Tặng kèm đồng hồ đo tốc độ Garmin Edge 130.',
                'quantity' => 1,
                'status' => 'published',
                'view_count' => 214,
                'images' => [
                    'images/products/giant-contend-ar4-1.png',
                    'images/products/giant-contend-ar4-2.png',
                    'images/products/giant-contend-ar4-3.png',
                    'images/products/giant-contend-ar4-4.png',
                    'images/products/giant-contend-ar4-5.png',
                ],
            ],
            [
                'name' => 'Mũ bảo hiểm fullface LS2 FF800 Storm',
                'category' => 'Xe cộ - Phụ tùng',
                'price' => 3200000,
                'original_price' => 4500000,
                'description' => 'Mũ bảo hiểm LS2 FF800 Storm size L, kính trong + kính đen, tiêu chuẩn ECE 22.05.',
                'short_description' => 'Mũ đội 5 chuyến, không va đập, lót khử mùi đã giặt.',
                'condition' => 'like_new',
                'location' => 'Quận 10, TP. HCM',
                'seller_name' => 'Lý Quốc Tuấn',
                'contact_phone' => '0905446688',
                'contact_email' => 'tuanly@example.com',
                'contact_method' => 'phone',
                'sku' => 'LS2-FF800-L-BLK',
                'origin' => 'LS2 Spain',
                'warranty' => '18 tháng',
                'attachments' => 'Túi đựng, kính đen, pinlock, sticker LS2',
                'additional_info' => 'Tặng găng tay bảo hộ Scoyco size L.',
                'quantity' => 1,
                'status' => 'published',
                'view_count' => 173,
                'images' => [
                    'images/products/ls2-ff800-storm-1.png',
                    'images/products/ls2-ff800-storm-2.png',
                    'images/products/ls2-ff800-storm-3.png',
                    'images/products/ls2-ff800-storm-4.png',
                    'images/products/ls2-ff800-storm-5.png',
                ],
            ],
        ];

        foreach ($products as $data) {
            $categoryId = $categoryMap[$data['category']] ?? null;

            if (!$categoryId) {
                continue;
            }

            $userId = $data['user_id'] ?? $userIds[array_rand($userIds)];

            $product = Product::create([
                'user_id' => $userId,
                'name' => $data['name'],
                'category_id' => $categoryId,
                'price' => $data['price'],
                'original_price' => $data['original_price'],
                'description' => $data['description'],
                'short_description' => $data['short_description'],
                'condition' => $data['condition'],
                'location' => $data['location'],
                'seller_name' => $data['seller_name'],
                'contact_phone' => $data['contact_phone'],
                'contact_email' => $data['contact_email'],
                'contact_method' => $data['contact_method'],
                'sku' => $data['sku'],
                'origin' => $data['origin'],
                'warranty' => $data['warranty'],
                'attachments' => $data['attachments'],
                'additional_info' => $data['additional_info'],
                'quantity' => $data['quantity'],
                'status' => $data['status'],
                'view_count' => $data['view_count'],
            ]);

            foreach ($data['images'] as $index => $imageUrl) {
                ProductImage::create([
                    'product_id' => $product->id,
                    'url' => $imageUrl,
                    'description' => 'Ảnh ' . ($index + 1) . ' cho ' . $data['name'],
                ]);
            }
        }
    }
}
