<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categoryMap = Category::pluck('id', 'name');
        $userIds = User::pluck('id')->all();

        if (empty($userIds) || $categoryMap->isEmpty()) {
            return;
        }

        $products = [
            [
                'name' => 'iPhone 13 128GB',
                'category' => 'Điện thoại',
                'price' => 18990000,
                'original_price' => 21990000,
                'description' => 'iPhone 13 phiên bản 128GB, máy chính hãng VN/A, pin 95%, ngoại hình đẹp, đầy đủ phụ kiện theo máy.',
                'short_description' => 'Máy còn bảo hành 6 tháng, đi kèm hộp và phụ kiện zin.',
                'condition' => 'like_new',
                'location' => 'Quận 1, TP. HCM',
                'seller_name' => 'Nguyễn Minh Huy',
                'contact_phone' => '0987123456',
                'contact_email' => 'minhhuy@example.com',
                'contact_method' => 'phone',
                'sku' => 'IP13-128-BK',
                'origin' => 'Chính hãng VN/A',
                'warranty' => '6 tháng',
                'attachments' => 'Hộp, cáp lightning, củ sạc Anker',
                'additional_info' => 'Giao hàng nội thành miễn phí, tặng kèm ốp lưng silicon.',
                'quantity' => 5,
                'image' => 'images/product_1.png',
                'status' => 'published',
                'view_count' => 245,
            ],
            [
                'name' => 'Samsung Galaxy S23 Ultra 256GB',
                'category' => 'Điện thoại',
                'price' => 25990000,
                'original_price' => 31990000,
                'description' => 'Galaxy S23 Ultra màu đen, máy dùng nhẹ 3 tháng, bút S-Pen đầy đủ, kính cường lực dán sẵn.',
                'short_description' => 'Máy 99%, phụ kiện tặng kèm, hỗ trợ trả góp.',
                'condition' => 'good',
                'location' => 'Cầu Giấy, Hà Nội',
                'seller_name' => 'Trần Thu Trang',
                'contact_phone' => '0912345678',
                'contact_email' => 'trangtran@example.com',
                'contact_method' => 'zalo',
                'sku' => 'SS-S23U-256-BK',
                'origin' => 'Chính hãng Samsung VN',
                'warranty' => '12 tháng',
                'attachments' => 'Hộp, cáp USB-C, bút S-Pen, ốp lưng trong',
                'additional_info' => 'Bao test 7 ngày, hỗ trợ ship toàn quốc.',
                'quantity' => 3,
                'image' => 'images/product_2.png',
                'status' => 'published',
                'view_count' => 312,
            ],
            [
                'name' => 'MacBook Pro 14" M1 Pro 16GB/512GB',
                'category' => 'Laptop',
                'price' => 12990000,
                'original_price' => 15990000,
                'description' => 'Xiaomi 12T Pro chip Snapdragon 8+ Gen 1, camera 200MP, hỗ trợ sạc nhanh 120W.',
                'short_description' => 'Máy chính hãng, kích hoạt 2 tháng, còn seal phụ kiện.',
                'condition' => 'good',
                'location' => 'Nam Từ Liêm, Hà Nội',
                'seller_name' => 'Phan Thanh Bình',
                'contact_phone' => '0905123456',
                'contact_email' => 'binhphan@example.com',
                'contact_method' => 'zalo',
                'sku' => 'XM-12TPRO-256-BL',
                'origin' => 'Xiaomi VN',
                'warranty' => '10 tháng',
                'attachments' => 'Hộp, sạc 120W, ốp lưng, kính cường lực',
                'additional_info' => 'Tặng gói bảo hành rơi vỡ 3 tháng.',
                'quantity' => 6,
                'image' => 'images/product_3.png',
                'status' => 'published',
                'view_count' => 134,
            ],
            [
                'name' => 'Dell XPS 13 9310 FHD+',
                'category' => 'Laptop',
                'price' => 2500000,
                'original_price' => 4500000,
                'description' => 'Áo khoác jacket North Face chính hãng, size L, màu đen, chống thấm nước tuyệt vời.',
                'short_description' => 'Áo mới 95%, đã giặt khô.',
                'condition' => 'like_new',
                'location' => 'Quận 1, TP. HCM',
                'seller_name' => 'Nguyễn Văn A',
                'contact_phone' => '0977665544',
                'contact_email' => 'vana@example.com',
                'contact_method' => 'phone',
                'sku' => 'NF-JACKET-L-BLK',
                'origin' => 'North Face USA',
                'warranty' => null,
                'attachments' => 'Tag chính hãng',
                'additional_info' => 'Phù hợp mùa đông, giữ ấm tốt.',
                'quantity' => 2,
                'image' => 'images/product_4.png',
                'status' => 'published',
                'view_count' => 156,
            ],
            [
                'name' => 'Giày Sneaker Nike Air Max 270',
                'category' => 'Thời trang',
                'price' => 1800000,
                'original_price' => 3200000,
                'description' => 'Giày Nike Air Max 270 size 42, màu trắng đen, đã mang 3 lần, còn rất mới.',
                'short_description' => 'Giày authentic, fullbox, phụ kiện đầy đủ.',
                'condition' => 'like_new',
                'location' => 'Bình Thạnh, TP. HCM',
                'seller_name' => 'Võ Bảo Trân',
                'contact_phone' => '0933557799',
                'contact_email' => 'baotran@example.com',
                'contact_method' => 'phone',
                'sku' => 'NIKE-AM270-42-WB',
                'origin' => 'Nike Store',
                'warranty' => null,
                'attachments' => 'Hộp, giấy gói, sticker',
                'additional_info' => 'Đế còn nguyên, không trầy xước.',
                'quantity' => 1,
                'image' => 'images/product_5.png',
                'status' => 'published',
                'view_count' => 89,
            ],
            [
                'name' => 'Túi xách Louis Vuitton Neverfull MM',
                'category' => 'Thời trang',
                'price' => 15000000,
                'original_price' => 32000000,
                'description' => 'Túi Louis Vuitton Neverfull MM size trung, họa tiết Monogram kinh điển, hàng authentic.',
                'short_description' => 'Túi chính hãng, kèm hóa đơn, 90% mới.',
                'condition' => 'good',
                'location' => 'Quận 1, TP. HCM',
                'seller_name' => 'Đặng Hoàng Phúc',
                'contact_phone' => '0944332211',
                'contact_email' => 'phucdang@example.com',
                'contact_method' => 'phone',
                'sku' => 'LV-NEVERFULL-MM-MONO',
                'origin' => 'Louis Vuitton France',
                'warranty' => null,
                'attachments' => 'Dustbag, hóa đơn cửa hàng',
                'additional_info' => 'Kiểm tra kỹ tại cửa hàng LV trước khi mua.',
                'quantity' => 1,
                'image' => 'images/product_6.png',
                'status' => 'published',
                'view_count' => 234,
            ],
            // ========== DANH MỤC 3: Đồ gia dụng (6 sản phẩm) ==========
            [
                'name' => 'Nồi cơm điện Cuckoo 1.8L',
                'category' => 'Đồ gia dụng',
                'price' => 2800000,
                'original_price' => 4200000,
                'description' => 'Nồi cơm điện Cuckoo áp suất 1.8L, công nghệ Hàn Quốc, nấu cơm ngon mềm.',
                'short_description' => 'Nồi còn mới 90%, dùng 6 tháng.',
                'condition' => 'good',
                'location' => 'Tân Bình, TP. HCM',
                'seller_name' => 'Ngô Anh Thư',
                'contact_phone' => '0968112233',
                'contact_email' => 'anhthu@example.com',
                'contact_method' => 'phone',
                'sku' => 'CUCKOO-1.8L-PRESS',
                'origin' => 'Cuckoo Korea',
                'warranty' => '6 tháng',
                'attachments' => 'Hộp, sách hướng dẫn, xửng hấp',
                'additional_info' => 'Tặng kèm 2kg gạo ST25.',
                'quantity' => 2,
                'image' => 'images/product_7.png',
                'status' => 'published',
                'view_count' => 176,
            ],
            [
                'name' => 'Máy lọc không khí Xiaomi 3H',
                'category' => 'Đồ gia dụng',
                'price' => 1900000,
                'original_price' => 2900000,
                'description' => 'Máy lọc không khí Xiaomi 3H, lọc PM 2.5, diện tích 45m2, hoạt động êm ái.',
                'short_description' => 'Máy còn mới 95%, thay lõi định kỳ.',
                'condition' => 'like_new',
                'location' => 'Nam Từ Liêm, Hà Nội',
                'seller_name' => 'Phan Thanh Bình',
                'contact_phone' => '0905123456',
                'contact_email' => 'binhphan@example.com',
                'contact_method' => 'zalo',
                'sku' => 'XIAOMI-3H-AIRPUR',
                'origin' => 'Xiaomi VN',
                'warranty' => '4 tháng',
                'attachments' => 'Hộp, bộ lọc HEPA mới',
                'additional_info' => 'Tặng kèm 1 bộ lọc thay thế.',
                'quantity' => 3,
                'image' => 'images/product_8.png',
                'status' => 'published',
                'view_count' => 98,
            ],
            // ========== DANH MỤC 4: Sách - Văn phòng phẩm (3 sản phẩm) ==========
            [
                'name' => 'Bộ sách Harry Potter 7 tập',
                'category' => 'Sách - Văn phòng phẩm',
                'price' => 650000,
                'original_price' => 1400000,
                'description' => 'Bộ sách Harry Potter 7 tập bìa cứng tiếng Việt, nhà xuất bản Trẻ, còn mới 99%.',
                'short_description' => 'Sách nguyên bộ, không rách, không ố vàng.',
                'condition' => 'like_new',
                'location' => 'Đống Đa, Hà Nội',
                'seller_name' => 'Trương Gia Khánh',
                'contact_phone' => '0911668899',
                'contact_email' => 'giakhanh@example.com',
                'contact_method' => 'phone',
                'sku' => 'HP-SET-7VOLS',
                'origin' => 'NXB Trẻ',
                'warranty' => null,
                'attachments' => 'Bọc plastic',
                'additional_info' => 'Tặng kèm bookmark Harry Potter.',
                'quantity' => 5,
                'image' => 'images/product_9.png',
                'status' => 'published',
                'view_count' => 145,
            ],
            // ========== DANH MỤC 5: Xe cộ - Phụ tùng (3 sản phẩm) ==========
            [
                'name' => 'Xe đạp Giant ATX 720 27.5"',
                'category' => 'Xe cộ - Phụ tùng',
                'price' => 4500000,
                'original_price' => 9000000,
                'description' => 'Xe đạp địa hình Giant ATX 720, khung nhôm siêu nhẹ, phanh đĩa dầu, số Shimano 24 cấp.',
                'short_description' => 'Xe còn mới 85%, bảo dưỡng định kỳ.',
                'condition' => 'good',
                'location' => 'Thủ Đức, TP. HCM',
                'seller_name' => 'Huỳnh Thảo Vy',
                'contact_phone' => '0922664477',
                'contact_email' => 'thaovy@example.com',
                'contact_method' => 'phone',
                'sku' => 'GIANT-ATX720-27.5',
                'origin' => 'Giant Taiwan',
                'warranty' => null,
                'attachments' => 'Khóa xe, bơm, bộ dụng cụ sửa chữa',
                'additional_info' => 'Tặng kèm mũ bảo hiểm và đèn xe.',
                'quantity' => 1,
                'image' => 'images/product_10.png',
                'status' => 'published',
                'view_count' => 187,
            ],
        ];

        foreach ($products as $data) {
            $categoryId = $categoryMap[$data['category']] ?? null;

            if (!$categoryId) {
                continue;
            }

            $userId = $data['user_id'] ?? $userIds[array_rand($userIds)];

            $product = Product::create([
                'user_id' => $userId,
                'name' => $data['name'],
                'category_id' => $categoryId,
                'price' => $data['price'],
                'original_price' => $data['original_price'],
                'description' => $data['description'],
                'short_description' => $data['short_description'],
                'condition' => $data['condition'],
                'location' => $data['location'],
                'seller_name' => $data['seller_name'],
                'contact_phone' => $data['contact_phone'],
                'contact_email' => $data['contact_email'],
                'contact_method' => $data['contact_method'],
                'sku' => $data['sku'],
                'origin' => $data['origin'],
                'warranty' => $data['warranty'],
                'attachments' => $data['attachments'],
                'additional_info' => $data['additional_info'],
                'quantity' => $data['quantity'],
                'status' => $data['status'],
                'view_count' => $data['view_count'],
            ]);

            ProductImage::create([
                'product_id' => $product->id,
                'url' => $data['image'],
                'description' => 'Ảnh đại diện cho ' . $data['name'],
            ]);
        }
    }
}
