<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categoryMap = Category::pluck('id', 'name');
        $userIds = User::pluck('id')->all();

        if (empty($userIds) || $categoryMap->isEmpty()) {
            return;
        }

        $products = [
            [
                'name' => 'iPhone 13 128GB',
                'category' => 'Điện thoại',
                'price' => 18990000,
                'original_price' => 21990000,
                'description' => 'iPhone 13 phiên bản 128GB, máy chính hãng VN/A, pin 95%, ngoại hình đẹp, đầy đủ phụ kiện theo máy.',
                'short_description' => 'Máy còn bảo hành 6 tháng, đi kèm hộp và phụ kiện zin.',
                'condition' => 'like_new',
                'location' => 'Quận 1, TP. HCM',
                'seller_name' => 'Nguyễn Minh Huy',
                'contact_phone' => '0987123456',
                'contact_email' => 'minhhuy@example.com',
                'contact_method' => 'phone',
                'sku' => 'IP13-128-BK',
                'origin' => 'Chính hãng VN/A',
                'warranty' => '6 tháng',
                'attachments' => 'Hộp, cáp lightning, củ sạc Anker',
                'additional_info' => 'Giao hàng nội thành miễn phí, tặng kèm ốp lưng silicon.',
                'quantity' => 5,
                'image' => 'images/product_1.png',
                'status' => 'published',
                'view_count' => 245,
            ],
            [
                'name' => 'Samsung Galaxy S23 Ultra 256GB',
                'category' => 'Điện thoại',
                'price' => 25990000,
                'original_price' => 31990000,
                'description' => 'Galaxy S23 Ultra màu đen, máy dùng nhẹ 3 tháng, bút S-Pen đầy đủ, kính cường lực dán sẵn.',
                'short_description' => 'Máy 99%, phụ kiện tặng kèm, hỗ trợ trả góp.',
                'condition' => 'good',
                'location' => 'Cầu Giấy, Hà Nội',
                'seller_name' => 'Trần Thu Trang',
                'contact_phone' => '0912345678',
                'contact_email' => 'trangtran@example.com',
                'contact_method' => 'zalo',
                'sku' => 'SS-S23U-256-BK',
                'origin' => 'Chính hãng Samsung VN',
                'warranty' => '12 tháng',
                'attachments' => 'Hộp, cáp USB-C, bút S-Pen, ốp lưng trong',
                'additional_info' => 'Bao test 7 ngày, hỗ trợ ship toàn quốc.',
                'quantity' => 3,
                'image' => 'images/product_2.png',
                'status' => 'published',
                'view_count' => 312,
            ],
            [
                'name' => 'MacBook Pro 14" M1 Pro 16GB/512GB',
                'category' => 'Laptop',
                'price' => 42990000,
                'original_price' => 48990000,
                'description' => 'MacBook Pro 14 inch chip M1 Pro, máy mua tháng 5/2024, pin 25 chu kỳ, nguyên bản.',
                'short_description' => 'Máy siêu mới, đầy đủ phụ kiện chính hãng.',
                'condition' => 'like_new',
                'location' => 'Quận 3, TP. HCM',
                'seller_name' => 'Lê Hải Nam',
                'contact_phone' => '0909988776',
                'contact_email' => 'hainam@example.com',
                'contact_method' => 'email',
                'sku' => 'MBP14-M1P-16-512',
                'origin' => 'Apple Store Singapore',
                'warranty' => '8 tháng',
                'attachments' => 'Hộp, sạc USB-C 96W, cable USB-C',
                'additional_info' => 'Có hóa đơn VAT, hỗ trợ nâng cấp RAM/SSD theo nhu cầu.',
                'quantity' => 2,
                'image' => 'images/product_3.png',
                'status' => 'published',
                'view_count' => 198,
            ],
            [
                'name' => 'Dell XPS 13 9310 FHD+',
                'category' => 'Laptop',
                'price' => 28990000,
                'original_price' => 34990000,
                'description' => 'Dell XPS 13 9310, CPU i7-1165G7, RAM 16GB, SSD 512GB, màn InfinityEdge FHD+.',
                'short_description' => 'Máy mỏng nhẹ, pin trâu, bảo hành hãng 9 tháng.',
                'condition' => 'good',
                'location' => 'Thanh Xuân, Hà Nội',
                'seller_name' => 'Phạm Đức Long',
                'contact_phone' => '0977665544',
                'contact_email' => 'longpham@example.com',
                'contact_method' => 'phone',
                'sku' => 'DXPS13-9310-FHD',
                'origin' => 'Chính hãng Dell VN',
                'warranty' => '9 tháng',
                'attachments' => 'Hộp, sạc type-C, túi chống sốc',
                'additional_info' => 'Miễn phí vệ sinh máy định kỳ 1 năm.',
                'quantity' => 4,
                'image' => 'images/product_4.png',
                'status' => 'published',
                'view_count' => 156,
            ],
            [
                'name' => 'AirPods Pro 2 (USB-C)',
                'category' => 'Phụ kiện',
                'price' => 5290000,
                'original_price' => 6490000,
                'description' => 'Tai nghe AirPods Pro 2 bản cổng USB-C, hàng mới nguyên seal, chưa kích hoạt.',
                'short_description' => 'Tai nghe mới 100%, đổi trả trong 15 ngày.',
                'condition' => 'new',
                'location' => 'Bình Thạnh, TP. HCM',
                'seller_name' => 'Võ Bảo Trân',
                'contact_phone' => '0933557799',
                'contact_email' => 'baotran@example.com',
                'contact_method' => 'phone',
                'sku' => 'APPRO2-USBC',
                'origin' => 'Apple VN',
                'warranty' => '12 tháng',
                'attachments' => 'Seal mới, hóa đơn điện tử',
                'additional_info' => 'Ship nhanh nội thành trong 2 giờ.',
                'quantity' => 10,
                'image' => 'images/product_5.png',
                'status' => 'pending',
                'view_count' => 64,
            ],
            [
                'name' => 'Chuột Logitech MX Master 3S',
                'category' => 'Phụ kiện',
                'price' => 2490000,
                'original_price' => 2990000,
                'description' => 'Logitech MX Master 3S bản Graphite, dùng 1 tuần, đầy đủ phụ kiện và bảo hành 11 tháng.',
                'short_description' => 'Chuột ergonomic cao cấp, hỗ trợ Flow, dùng như mới.',
                'condition' => 'like_new',
                'location' => 'Đống Đa, Hà Nội',
                'seller_name' => 'Đặng Hoàng Phúc',
                'contact_phone' => '0944332211',
                'contact_email' => 'phucdang@example.com',
                'contact_method' => 'zalo',
                'sku' => 'LOGI-MX3S-GR',
                'origin' => 'Logitech VN',
                'warranty' => '11 tháng',
                'attachments' => 'Hộp, receiver Logi Bolt, cable USB-C',
                'additional_info' => 'Tặng kèm mousepad da.',
                'quantity' => 7,
                'image' => 'images/product_6.png',
                'status' => 'hidden',
                'view_count' => 88,
            ],
            [
                'name' => 'Asus ROG Strix G15 G513',
                'category' => 'Laptop',
                'price' => 35990000,
                'original_price' => 39990000,
                'description' => 'Laptop gaming Asus ROG Strix G15, Ryzen 9 5900HX, RTX 3070, RAM 16GB, SSD 1TB.',
                'short_description' => 'Máy gaming mạnh mẽ, tặng kèm balo ROG.',
                'condition' => 'good',
                'location' => 'Thủ Đức, TP. HCM',
                'seller_name' => 'Ngô Anh Thư',
                'contact_phone' => '0968112233',
                'contact_email' => 'anhthu@example.com',
                'contact_method' => 'phone',
                'sku' => 'ROG-G15-5900HX',
                'origin' => 'Chính hãng Asus',
                'warranty' => '10 tháng',
                'attachments' => 'Hộp, sạc 240W, balo ROG, chuột ROG Impact',
                'additional_info' => 'Bao test game FPS cao, hỗ trợ nâng RAM.',
                'quantity' => 3,
                'image' => 'images/product_7.png',
                'status' => 'published',
                'view_count' => 421,
            ],
            [
                'name' => 'Xiaomi 12T Pro 256GB',
                'category' => 'Điện thoại',
                'price' => 12990000,
                'original_price' => 15990000,
                'description' => 'Xiaomi 12T Pro chip Snapdragon 8+ Gen 1, camera 200MP, hỗ trợ sạc nhanh 120W.',
                'short_description' => 'Máy chính hãng, kích hoạt 2 tháng, còn seal phụ kiện.',
                'condition' => 'good',
                'location' => 'Nam Từ Liêm, Hà Nội',
                'seller_name' => 'Phan Thanh Bình',
                'contact_phone' => '0905123456',
                'contact_email' => 'binhphan@example.com',
                'contact_method' => 'zalo',
                'sku' => 'XM-12TPRO-256-BL',
                'origin' => 'Xiaomi VN',
                'warranty' => '10 tháng',
                'attachments' => 'Hộp, sạc 120W, ốp lưng, kính cường lực',
                'additional_info' => 'Tặng gói bảo hành rơi vỡ 3 tháng.',
                'quantity' => 6,
                'image' => 'images/product_8.png',
                'status' => 'published',
                'view_count' => 134,
            ],
            [
                'name' => 'Keychron K6 Wireless RGB',
                'category' => 'Phụ kiện',
                'price' => 2190000,
                'original_price' => 2490000,
                'description' => 'Bàn phím cơ Keychron K6 RGB switch Gateron Brown, layout 65%, kết nối Bluetooth 5.1.',
                'short_description' => 'Phím cơ đa dụng, đã mod foam và lube stab.',
                'condition' => 'fair',
                'location' => 'Tân Bình, TP. HCM',
                'seller_name' => 'Trương Gia Khánh',
                'contact_phone' => '0911668899',
                'contact_email' => 'giakhanh@example.com',
                'contact_method' => 'phone',
                'sku' => 'KEY-K6-RGB-BR',
                'origin' => 'Keychron Official',
                'warranty' => '3 tháng',
                'attachments' => 'Hộp, cable USB-C, keycap puller',
                'additional_info' => 'Tặng kèm set keycap PBT trắng xám.',
                'quantity' => 8,
                'image' => 'images/product_9.png',
                'status' => 'hidden',
                'view_count' => 57,
            ],
            [
                'name' => 'Surface Laptop 5 13.5" i5/8GB/512GB',
                'category' => 'Laptop',
                'price' => 26990000,
                'original_price' => 31990000,
                'description' => 'Surface Laptop 5 phiên bản màu Platinum, màn cảm ứng 13.5 inch, dùng văn phòng nhẹ, pin 16 giờ.',
                'short_description' => 'Máy đẹp 99%, bảo hành Microsoft chính hãng.',
                'condition' => 'like_new',
                'location' => 'Hải Châu, Đà Nẵng',
                'seller_name' => 'Huỳnh Thảo Vy',
                'contact_phone' => '0922664477',
                'contact_email' => 'thaovy@example.com',
                'contact_method' => 'email',
                'sku' => 'SURFL5-13-i5-512',
                'origin' => 'Microsoft Store',
                'warranty' => '11 tháng',
                'attachments' => 'Hộp, sạc Surface, bút Surface Slim Pen 2',
                'additional_info' => 'Tặng kèm túi chống sốc và chuột Surface Arc.',
                'quantity' => 4,
                'image' => 'images/product_10.png',
                'status' => 'sold',
                'view_count' => 502,
            ],
        ];

        foreach ($products as $data) {
            $categoryId = $categoryMap[$data['category']] ?? null;

            if (!$categoryId) {
                continue;
            }

            $userId = $data['user_id'] ?? $userIds[array_rand($userIds)];

            $product = Product::create([
                'user_id' => $userId,
                'name' => $data['name'],
                'category_id' => $categoryId,
                'price' => $data['price'],
                'original_price' => $data['original_price'],
                'description' => $data['description'],
                'short_description' => $data['short_description'],
                'condition' => $data['condition'],
                'location' => $data['location'],
                'seller_name' => $data['seller_name'],
                'contact_phone' => $data['contact_phone'],
                'contact_email' => $data['contact_email'],
                'contact_method' => $data['contact_method'],
                'sku' => $data['sku'],
                'origin' => $data['origin'],
                'warranty' => $data['warranty'],
                'attachments' => $data['attachments'],
                'additional_info' => $data['additional_info'],
                'quantity' => $data['quantity'],
                'status' => $data['status'],
                'view_count' => $data['view_count'],
            ]);

            ProductImage::create([
                'product_id' => $product->id,
                'url' => $data['image'],
                'description' => 'Ảnh đại diện cho ' . $data['name'],
            ]);
        }
    }
}
